### ISSUE TITLE
If an Avro schema has a namespace, that's not set in the Java model's package declaration.

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/java-spring-cloud-stream-template#174]
#### Describe the bug
The last feature implemented was to improve Avro support. We do look at the Avro schema's namespace and put the file into the right directory. However we forgot to change the Java package declaration in that file.

#### How to Reproduce
Run a file containing something like this:
```
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          name: User
          namespace: com.example.publisher
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
```

It is expected that the User class file ends up in the 'com.example.publisher' package and has the line
```
package com.example.publisher;
```
but the package name isn't changed from the one set by the `javaPackage` parameter.

#### Expected behavior
The declared package should match the Avro namespace.
