### ISSUE TITLE
The model of externalDocs can't be generated successfully

### ISSUE THREAD

**Issue by max2liu** [asyncapi/java-spring-cloud-stream-template#314]
#### Describe the bug
The model of externalDocs can't be generated successfully

#### How to Reproduce
1. async api docs:
```yaml
  schemas:
    PersonUpdatedEvent:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
          description: Id of event.
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
        personDto:
          type: object
          externalDocs:
            description: ''
            url: "D:/Source/AsyncAPI/Common.yaml#/components/schemas/PersonDto"
```
2. externalDocs yaml:
```yaml
  schemas:
    PersonDto:
      type: object
      properties:
        name:
          type: string
          minimum: 6
          description: Name of person.
        title:
          type: string
          example: MANAGER
          enum:
            - MANAGER
            - TEAM_LEADER
            - TECHNICAL_ENGINEER
```
3. generated code:
![image](https://user-images.githubusercontent.com/25974214/206609037-54e25971-5133-49c7-96f6-ea420d21e3d6.png)

#### Expected behavior
The code of PersonDto should contains the related fields of its properties
