### ISSUE TITLE
Need to check that generated class names are not common java.lang class names

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/java-spring-cloud-stream-template#36]
#### Describe the bug
A user defined an enum called 'string', which caused the generator to generate
```public static enum String { ... }```

#### How to Reproduce
Create a document that has a property like:
```
        status:
          default: OK
          examples:
            - OK
          pattern: ^(.*)$
          type: string
          title: The Status Schema
          enum:
            - OK
            - STOP
            - FAIL
            - START
            - STOPPED
            - FLAT_TIRE
            - ENGINE_PROBLEM
```

#### Expected behavior
The generator should use the property name (status) not the type (string) when generating the enum class name.
