### ISSUE TITLE
Update Binder Config Location

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#44]
It would be ideal if the template would put the binder connection information under `spring.cloud.stream.binders` instead of under `solace.java` or wherever Rabbit/Kafka go by default. By putting them under this new location it allows for the generated app to more easily be modified to use multiple binders. 

With this change I would expect the generated config to look something like this: 

```
spring:
  cloud:
    function:
      definition: uppercase
    stream:
      bindings:
        uppercase-in-0:
          destination: queuename
          group: myconsumergroup
          binder: solace-broker
        uppercase-out-0:
          destination: uppercase/topic
          binder: solace-broker
      binders:
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1
```
